package view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author zfabi
 */
public class JDlgIffFornecedor extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDlgIffFornecedor.class.getName());

    /**
     * Creates new form JDlgFornecedor
     */
    public JDlgIffFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setTitle("Cadastro de Fornecedor");
        setLocationRelativeTo(null);

        jTxtIffCidade.setEnabled(false);
        jTxtIffCodigo.setEnabled(false);
        jTxtIffEmail.setEnabled(false);
        jTxtIffEndereco.setEnabled(false);
        jFmtIffCEP.setEnabled(false);
        jTxtIffEstado.setEnabled(false);
        jTxtIffCidade.setEnabled(false);
        jTxtIffEndereco.setEnabled(false);
        jTxtIffICMS.setEnabled(false);
        jTxtIffEmail.setEnabled(false);
        jFmtIffDataCadastro.setEnabled(false);
        jFmtIffCNPJ.setEnabled(false);
        jFmtIffDataCadastro.setEnabled(false);
        jCboIffNivel.setEnabled(false);
        jTxtIffPais.setEnabled(false);
        jTxtIffTelefone.setEnabled(false);
        jTxtIffRepresentante.setEnabled(false);
        jTxtIffNomeFantasia.setEnabled(false);
        jTxtIffNomeEmpresa.setEnabled(false);
        jBtnIffPesquisar.setEnabled(true);
        jBtnIffExcluir.setEnabled(true);
        jBtnIffAlterar.setEnabled(true);
        jBtnIffIncluir.setEnabled(true);
    }

    public void habilitar(boolean valor) {
        jTxtIffCidade.setEnabled(valor);
        jTxtIffCodigo.setEnabled(valor);
        jTxtIffEmail.setEnabled(valor);
        jTxtIffEndereco.setEnabled(valor);
        jFmtIffCEP.setEnabled(valor);
        jTxtIffEstado.setEnabled(valor);
        jTxtIffCidade.setEnabled(valor);
        jTxtIffEndereco.setEnabled(valor);
        jTxtIffICMS.setEnabled(valor);
        jTxtIffEmail.setEnabled(valor);
        jFmtIffDataCadastro.setEnabled(valor);
        jFmtIffCNPJ.setEnabled(valor);
        jFmtIffDataCadastro.setEnabled(valor);
        jCboIffNivel.setEnabled(valor);
        jTxtIffPais.setEnabled(valor);
        jTxtIffTelefone.setEnabled(valor);
        jTxtIffRepresentante.setEnabled(valor);
        jTxtIffNomeFantasia.setEnabled(valor);
        jTxtIffNomeEmpresa.setEnabled(valor);
        jBtnIffPesquisar.setEnabled(!valor);
        jBtnIffExcluir.setEnabled(!valor);
        jBtnIffAlterar.setEnabled(!valor);
        jBtnIffIncluir.setEnabled(!valor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jCboIffNivel = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTxtIffCodigo = new javax.swing.JTextField();
        jTxtIffNomeEmpresa = new javax.swing.JTextField();
        jTxtIffNomeFantasia = new javax.swing.JTextField();
        jTxtIffEmail = new javax.swing.JTextField();
        jTxtIffTelefone = new javax.swing.JTextField();
        jTxtIffEndereco = new javax.swing.JTextField();
        jTxtIffCidade = new javax.swing.JTextField();
        jTxtIffEstado = new javax.swing.JTextField();
        jTxtIffPais = new javax.swing.JTextField();
        jFmtIffCEP = new javax.swing.JFormattedTextField();
        jTxtIffRepresentante = new javax.swing.JTextField();
        jFmtIffCNPJ = new javax.swing.JFormattedTextField();
        jFmtIffDataCadastro = new javax.swing.JFormattedTextField();
        jTxtIffICMS = new javax.swing.JTextField();
        jBtnIffIncluir = new javax.swing.JButton();
        jBtnIffAlterar = new javax.swing.JButton();
        jBtnIffExcluir = new javax.swing.JButton();
        jBtnIffConfirmar = new javax.swing.JButton();
        jBtnIffCancelar = new javax.swing.JButton();
        jBtnIffPesquisar = new javax.swing.JButton();

        jTextField5.setText("jTextField5");


        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Codigo");

        jLabel2.setText("Nome da Empresa");

        jLabel3.setText("Email");

        jLabel4.setText("Telefone");

        jLabel5.setText("Endereço");

        jLabel6.setText("Cidade");

        jLabel7.setText("Estado");

        jLabel8.setText("CEP");

        jLabel9.setText("País");

        jLabel10.setText("CNPJ");

        jLabel11.setText("Representante");

        jLabel13.setText("Nome Fantasia");

        jLabel14.setText("Data de Cadastro");

        jCboIffNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setText("Nível");

        jLabel16.setText("ICMS");

        jBtnIffIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIffIncluir.setText("Incluir");
        jBtnIffIncluir.addActionListener(this::jBtnIffIncluirActionPerformed);

        jBtnIffAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnIffAlterar.setText("Alterar");
        jBtnIffAlterar.addActionListener(this::jBtnIffAlterarActionPerformed);

        jBtnIffExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnIffExcluir.setText("Excluir");
        jBtnIffExcluir.addActionListener(this::jBtnIffExcluirActionPerformed);

        jBtnIffConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnIffConfirmar.setText("Confirmar");
        jBtnIffConfirmar.addActionListener(this::jBtnIffConfirmarActionPerformed);

        jBtnIffCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnIffCancelar.setText("Cancelar");
        jBtnIffCancelar.addActionListener(this::jBtnIffCancelarActionPerformed);

        jBtnIffPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnIffPesquisar.setText("Pesquisar");
        jBtnIffPesquisar.addActionListener(this::jBtnIffPesquisarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtIffEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jTxtIffCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jTxtIffEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jFmtIffCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(31, 31, 31))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTxtIffCodigo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTxtIffNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(jTxtIffNomeFantasia)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jFmtIffDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTxtIffRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel15)
                                                    .addComponent(jCboIffNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(49, 49, 49)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel16)
                                                    .addComponent(jTxtIffICMS, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(24, 24, 24)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtIffEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(jTxtIffTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jTxtIffPais, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(10, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnIffIncluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnIffAlterar)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnIffExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnIffConfirmar)
                                .addGap(12, 12, 12)
                                .addComponent(jBtnIffCancelar)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnIffPesquisar))
                            .addComponent(jFmtIffCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtIffCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtIffNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtIffNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtIffEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtIffTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtIffPais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtIffEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtIffCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtIffEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFmtIffCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtIffRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtIffCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCboIffNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtIffDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtIffICMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIffIncluir)
                    .addComponent(jBtnIffAlterar)
                    .addComponent(jBtnIffExcluir)
                    .addComponent(jBtnIffConfirmar)
                    .addComponent(jBtnIffCancelar)
                    .addComponent(jBtnIffPesquisar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIffConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIffConfirmarActionPerformed
        // TODO add your handling code here:
        habilitar(!rootPaneCheckingEnabled);
    }//GEN-LAST:event_jBtnIffConfirmarActionPerformed

    private void jBtnIffCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIffCancelarActionPerformed
        // TODO add your handling code here:
        habilitar(!rootPaneCheckingEnabled);
    }//GEN-LAST:event_jBtnIffCancelarActionPerformed

    private void jBtnIffPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIffPesquisarActionPerformed
        // TODO add your handling code here:
        habilitar(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jBtnIffPesquisarActionPerformed

    private void jBtnIffIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIffIncluirActionPerformed
        // TODO add your handling code here:
        habilitar(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jBtnIffIncluirActionPerformed

    private void jBtnIffAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIffAlterarActionPerformed
        // TODO add your handling code here:
        habilitar(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jBtnIffAlterarActionPerformed

    private void jBtnIffExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIffExcluirActionPerformed
        // TODO add your handling code here:
        habilitar(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jBtnIffExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDlgIffFornecedor dialog = new JDlgIffFornecedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnIffAlterar;
    private javax.swing.JButton jBtnIffCancelar;
    private javax.swing.JButton jBtnIffConfirmar;
    private javax.swing.JButton jBtnIffExcluir;
    private javax.swing.JButton jBtnIffIncluir;
    private javax.swing.JButton jBtnIffPesquisar;
    private javax.swing.JComboBox<String> jCboIffNivel;
    private javax.swing.JFormattedTextField jFmtIffCEP;
    private javax.swing.JFormattedTextField jFmtIffCNPJ;
    private javax.swing.JFormattedTextField jFmtIffDataCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTxtIffCidade;
    private javax.swing.JTextField jTxtIffCodigo;
    private javax.swing.JTextField jTxtIffEmail;
    private javax.swing.JTextField jTxtIffEndereco;
    private javax.swing.JTextField jTxtIffEstado;
    private javax.swing.JTextField jTxtIffICMS;
    private javax.swing.JTextField jTxtIffNomeEmpresa;
    private javax.swing.JTextField jTxtIffNomeFantasia;
    private javax.swing.JTextField jTxtIffPais;
    private javax.swing.JTextField jTxtIffRepresentante;
    private javax.swing.JTextField jTxtIffTelefone;
    // End of variables declaration//GEN-END:variables
}
