/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

/**
 *
 * @author zfabi
 */
public class JDlgIffUsuarios extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDlgIffUsuarios.class.getName());

    /**
     * Creates new form JDlgIffUsuarios
     */
    public JDlgIffUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
                setTitle("Cadastro de Usuarios");
        setLocationRelativeTo(null);
        
        jTxtIffNome.setEnabled(false);
        jTxtIffCodigo.setEnabled(false);
        jTxtIffApelido.setEnabled(false);
        jTxtIffBairro.setEnabled(false);
        jFmtIffCPF.setEnabled(false);
        jTxtIffBairro.setEnabled(false);
        jTxtIffCidade.setEnabled(false);
        jTxtIffEndereco.setEnabled(false);
        jTxtIffNumero.setEnabled(false);
        jTxtIffEmail.setEnabled(false);
        jFmtIffCEP.setEnabled(false);
        jFmtIffCelular.setEnabled(false);
        jFmtIffDataCadastro.setEnabled(false);
        jFmtIffDataNascimento.setEnabled(false);
        jFmtIffRG.setEnabled(false);
        jFmtIffTelefone.setEnabled(false);
        jPwfSenha.setEnabled(false);
        jCboIffSexo.setEnabled(false);
        jChbIffAtivo.setEnabled(false);
        jBtnIffPesquisar.setEnabled(true);
        jBtnIffExcluir.setEnabled(true);
        jBtnIffAlterar.setEnabled(true);
        jBtnIffIncluir.setEnabled(true);
    }
    public void habilitar(boolean valor){
        jTxtIffNome.setEnabled(valor);
        jTxtIffCodigo.setEnabled(valor);
        jTxtIffApelido.setEnabled(valor);
        jTxtIffBairro.setEnabled(valor);
        jFmtIffCPF.setEnabled(valor);
        jTxtIffBairro.setEnabled(valor);
        jTxtIffCidade.setEnabled(valor);
        jTxtIffEndereco.setEnabled(valor);
        jTxtIffNumero.setEnabled(valor);
        jTxtIffEmail.setEnabled(valor);
        jFmtIffCEP.setEnabled(valor);
        jFmtIffCelular.setEnabled(valor);
        jFmtIffDataCadastro.setEnabled(valor);
        jFmtIffDataNascimento.setEnabled(valor);
        jFmtIffRG.setEnabled(valor);
        jFmtIffTelefone.setEnabled(valor);
        jPwfSenha.setEnabled(valor);     
        jCboIffSexo.setEnabled(valor);
        jChbIffAtivo.setEnabled(valor);
        jBtnIffPesquisar.setEnabled(!valor);
        jBtnIffExcluir.setEnabled(!valor);
        jBtnIffAlterar.setEnabled(!valor);
        jBtnIffIncluir.setEnabled(!valor);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtIffCodigo = new javax.swing.JTextField();
        jTxtIffNome = new javax.swing.JTextField();
        jTxtIffApelido = new javax.swing.JTextField();
        jTxtIffEmail = new javax.swing.JTextField();
        jFmtIffCelular = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTxtIffEndereco = new javax.swing.JTextField();
        jTxtIffNumero = new javax.swing.JTextField();
        jTxtIffBairro = new javax.swing.JTextField();
        jFmtIffCEP = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jFmtIffTelefone = new javax.swing.JFormattedTextField();
        jFmtIffCPF = new javax.swing.JFormattedTextField();
        jFmtIffRG = new javax.swing.JFormattedTextField();
        jFmtIffDataNascimento = new javax.swing.JFormattedTextField();
        jFmtIffDataCadastro = new javax.swing.JFormattedTextField();
        jCboIffSexo = new javax.swing.JComboBox<>();
        jPwfSenha = new javax.swing.JPasswordField();
        jChbIffAtivo = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jTxtIffCidade = new javax.swing.JTextField();
        jBtnIffAlterar = new javax.swing.JButton();
        jBtnIffExcluir = new javax.swing.JButton();
        jBtnIffIncluir = new javax.swing.JButton();
        jBtnIffConfirmar = new javax.swing.JButton();
        jBtnIffPesquisar = new javax.swing.JButton();
        jBtnIffCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Codigo");

        jLabel2.setText("Nome");

        jLabel3.setText("Apelido");

        jLabel4.setText("Email");

        jLabel5.setText("Celular");

        jTxtIffNome.addActionListener(this::jTxtIffNomeActionPerformed);

        jLabel6.setText("Endereço");

        jLabel7.setText("Número");

        jLabel8.setText("Bairro");

        jLabel9.setText("CEP");

        jTxtIffNumero.addActionListener(this::jTxtIffNumeroActionPerformed);

        jLabel10.setText("CPF");

        jLabel11.setText("RG");

        jLabel12.setText("Senha");

        jLabel13.setText("Data de Nascimento");

        jLabel14.setText("Data de Cadastro");

        jLabel15.setText("Sexo");

        jLabel16.setText("Telefone");

        jFmtIffCPF.addActionListener(this::jFmtIffCPFActionPerformed);

        jCboIffSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCboIffSexo.addActionListener(this::jCboIffSexoActionPerformed);

        jPwfSenha.setText("jPasswordField1");

        jChbIffAtivo.setText("Ativo");
        jChbIffAtivo.addActionListener(this::jChbIffAtivoActionPerformed);

        jLabel17.setText("Cidade");

        jTxtIffCidade.addActionListener(this::jTxtIffCidadeActionPerformed);

        jBtnIffAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnIffAlterar.setText("Alterar");
        jBtnIffAlterar.addActionListener(this::jBtnIffAlterarActionPerformed);

        jBtnIffExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnIffExcluir.setText("Excluir");
        jBtnIffExcluir.addActionListener(this::jBtnIffExcluirActionPerformed);

        jBtnIffIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIffIncluir.setText("Incluir");
        jBtnIffIncluir.addActionListener(this::jBtnIffIncluirActionPerformed);

        jBtnIffConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnIffConfirmar.setText("Confirmar");
        jBtnIffConfirmar.addActionListener(this::jBtnIffConfirmarActionPerformed);

        jBtnIffPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnIffPesquisar.setText("Pesquisar");
        jBtnIffPesquisar.addActionListener(this::jBtnIffPesquisarActionPerformed);

        jBtnIffCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnIffCancelar.setText("Cancelar");
        jBtnIffCancelar.addActionListener(this::jBtnIffCancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jTxtIffCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jTxtIffNome, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(jLabel7))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11))
                                    .addComponent(jTxtIffEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jTxtIffNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTxtIffApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jTxtIffBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jFmtIffCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addGap(169, 169, 169))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jTxtIffEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jFmtIffTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(117, 117, 117)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel17)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addComponent(jTxtIffCidade))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jFmtIffCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(82, 82, 82)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jCboIffSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(118, 118, 118))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel15)
                                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                                .addGap(91, 91, 91))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jFmtIffCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFmtIffRG, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jFmtIffDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jFmtIffDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 399, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPwfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jChbIffAtivo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jBtnIffIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jBtnIffAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnIffExcluir)
                        .addGap(29, 29, 29)
                        .addComponent(jBtnIffConfirmar)
                        .addGap(40, 40, 40)
                        .addComponent(jBtnIffCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnIffPesquisar)
                        .addGap(215, 215, 215))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtIffCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtIffNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtIffApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtIffEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtIffTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtIffEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtIffNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtIffBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtIffCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtIffCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtIffCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmtIffDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnIffAlterar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBtnIffConfirmar)
                                .addComponent(jBtnIffCancelar)
                                .addComponent(jBtnIffPesquisar)
                                .addComponent(jBtnIffExcluir)))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFmtIffCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtIffRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtIffDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCboIffSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPwfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jChbIffAtivo))
                        .addGap(18, 18, 18)
                        .addComponent(jBtnIffIncluir)
                        .addContainerGap(19, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtIffNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtIffNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtIffNomeActionPerformed

    private void jChbIffAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbIffAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChbIffAtivoActionPerformed

    private void jTxtIffCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtIffCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtIffCidadeActionPerformed

    private void jTxtIffNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtIffNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtIffNumeroActionPerformed

    private void jFmtIffCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtIffCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtIffCPFActionPerformed

    private void jCboIffSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboIffSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboIffSexoActionPerformed

    private void jBtnIffPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIffPesquisarActionPerformed
        // TODO add your handling code here:
        habilitar(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jBtnIffPesquisarActionPerformed

    private void jBtnIffIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIffIncluirActionPerformed
        // TODO add your handling code here:
        habilitar(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jBtnIffIncluirActionPerformed

    private void jBtnIffAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIffAlterarActionPerformed
        // TODO add your handling code here:
        habilitar(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jBtnIffAlterarActionPerformed

    private void jBtnIffExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIffExcluirActionPerformed
        // TODO add your handling code here:
        habilitar(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jBtnIffExcluirActionPerformed

    private void jBtnIffConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIffConfirmarActionPerformed
        // TODO add your handling code here:
        habilitar(!rootPaneCheckingEnabled);
    }//GEN-LAST:event_jBtnIffConfirmarActionPerformed

    private void jBtnIffCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIffCancelarActionPerformed
        // TODO add your handling code here:
        habilitar(!rootPaneCheckingEnabled);
    }//GEN-LAST:event_jBtnIffCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDlgIffUsuarios dialog = new JDlgIffUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnIffAlterar;
    private javax.swing.JButton jBtnIffCancelar;
    private javax.swing.JButton jBtnIffConfirmar;
    private javax.swing.JButton jBtnIffExcluir;
    private javax.swing.JButton jBtnIffIncluir;
    private javax.swing.JButton jBtnIffPesquisar;
    private javax.swing.JComboBox<String> jCboIffSexo;
    private javax.swing.JCheckBox jChbIffAtivo;
    private javax.swing.JFormattedTextField jFmtIffCEP;
    private javax.swing.JFormattedTextField jFmtIffCPF;
    private javax.swing.JFormattedTextField jFmtIffCelular;
    private javax.swing.JFormattedTextField jFmtIffDataCadastro;
    private javax.swing.JFormattedTextField jFmtIffDataNascimento;
    private javax.swing.JFormattedTextField jFmtIffRG;
    private javax.swing.JFormattedTextField jFmtIffTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPwfSenha;
    private javax.swing.JTextField jTxtIffApelido;
    private javax.swing.JTextField jTxtIffBairro;
    private javax.swing.JTextField jTxtIffCidade;
    private javax.swing.JTextField jTxtIffCodigo;
    private javax.swing.JTextField jTxtIffEmail;
    private javax.swing.JTextField jTxtIffEndereco;
    private javax.swing.JTextField jTxtIffNome;
    private javax.swing.JTextField jTxtIffNumero;
    // End of variables declaration//GEN-END:variables
}
